### ISSUE TITLE
File Transfer caused plugin bug?

### ISSUE THREAD

**Issue by Castiella** [AddstarMC/Minigames#110]
I recently transferred all of our files over to a new server host,

Since then, the minigames won't load. I have checked over and over - everything was copied correctly.

To elaborate - 
When you do /mg list - it gives you a blank response. 
When you click a pre-existing minigame sign - it says " Minigame does not exist!"
Same when trying /mg edit ect.

Any ideas on how to fix this? I will gladly pay you guys if a resolution is found - we have 3 years worth of work lost due to this and are desperate.

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC

**Comment by Narimm** [comment]
You will need to attach the server.log report that contains the error message for us to attempt to review this..also attach the config that causes an error

**Comment by Narimm** [comment]
Btw best guess is its a permissions based error

**Comment by alchemistmatt** [comment]
Also be sure to check the database configuration.  If the Minigames config.yml mentions MySQL for the backend, then you need to get your database properly configured.  Error messages at console will also provide clues to the issue.

**Comment by Castiella** [comment]
I put it in spigot discussion a month ago and got no response.
Read the Wiki and got no joy either.

i haven't made any edits to the config or permissions. 

I'm also not getting any console error messages.
I have attached the recent server log and config.yml

[config.txt](https://github.com/AddstarMC/Minigames/files/1065138/config.txt)

[latest.txt](https://github.com/AddstarMC/Minigames/files/1065141/latest.txt)

Nothing about MySQL in the config by the looks of it either.

**Comment by alchemistmatt** [comment]
According to config.txt, your database backend is `sqlite` -- see the `backend` section in your config file (which, by the way, should be named `config.yml` and not `config.txt`).  There is a console error from LWC regarding SQLite: `Failed to load native library:libsqlitejdbc.so. osinfo: Linux/x86_64` so that's concerning.  To confirm that SQLite is installed and working use `sqlite3` from your shell prompt.  If missing, google "install sqlite3" with your OS name.  Finally, note that `minigames: {}` indicates that no minigames are defined, but if the configuration is defined in the SQLite database, then that might be normal.

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.
We monitor this thread as well, as do other users of the plugin.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC

**Comment by Castiella** [comment]
I had to convert the files to txt as it wouldn't let me upload them here as yml.

also, im confused with "o confirm that SQLite is installed and working use sqlite3 from your shell prompt. If missing, google "install sqlite3" with your OS name. Finally, note that minigames: {} indicates that no minigames are defined, but if the configuration is defined in the SQLite database, then that might be normal."

I don't know what you mean? The server has a dedicated host, so where would i locate the shell prompt?
I don't even know what an OS name is?

if it helps there is a miniames.db within my console files....

**Comment by Castiella** [comment]
As for Narimm, I don't see how this isn't a bug? I moved everything over between servers and now the minigame plugin isnt working properly

**Comment by Castiella** [comment]
I'm literally willing to pay you guys to get this sorted, honestly its driving me mad

**Comment by Narimm** [comment]
1. It isnt a bug because you actually havent shown me an area of code that is preventing it running 
2, Your running Paper...I have never tested it against paper and have no idea of the inbuilt librarires paper ships with...
3. You have craftbukkit 1.7 as a plugin on a 1.11.2 server.....is that some sort of test? 
4.  If it was working on the same setup before you moved servers...the problem isnt in the PLUGIN its how you moved servers...again CONFIGURATION

Finally - you plugins are all out of date using deprecated classes 

I could go on but i wont because we dont provide server configuration classes here....
