### ISSUE TITLE
"Max Users" option for teams not working?

### ISSUE THREAD

**Issue by Noahkiq** [AddstarMC/Minigames#139]
I've setup a map to have two teams where one of the teams has a max player count of 1. However, more than one player can still join the team. I've tried testing this on different maps with different settings applied but can't get the option to actually work.

**Comment by Narimm** [comment]
Is it assigning more than 1 player to a team or are u using a command or sign to allow players to join a team if so what command and what sign plugin

**Comment by Noahkiq** [comment]
The plugin's automatically assigning more than one player to a team. I
haven't use any signs, but if I was, I'd use the built-in Minigame Team
Join sign

**Comment by Narimm** [comment]
To assist with diagnosis: 

You will need to attach the server.log report that contains the error message for us to attempt to review this..also attach the config that causes an error (use pastebin).  If there is no error...please attach a serverlog (using pastebin)  that shows spigot version/ minigames version and the log file when the issue occurs with `/minigame debug` active

Sincerely
AddstarMC Admin

**Comment by Pugabyte** [comment]
I believe this is due to most mechanics not having team#isFull checks. [Infection does](https://github.com/AddstarMC/Minigames/blob/master/Minigames/src/main/java/au/com/mineauz/minigames/mechanics/InfectionMechanic.java#L66) but [juggernaut](https://github.com/AddstarMC/Minigames/blob/master/Minigames/src/main/java/au/com/mineauz/minigames/mechanics/JuggernautMechanic.java) does not.

**Comment by Narimm** [comment]
Outdated build please try the latest and recheck and reopen of still causing issues
