### ISSUE TITLE
Minigames causing lag?

### ISSUE THREAD

**Issue by Castiella** [AddstarMC/Minigames#168]
* **I'm submitting a ... **
  - [ X] bug report
  - [ ] feature request

Hi, I think minigames is running some lag on my server (at the bottom of the timings)

https://timings.aikar.co/?id=fc7b66845570448cb868adbe02c5862d

could you help by telling me what is the issue? im using the lastest build.

**Comment by Narimm** [comment]
Sorry I dont see it...however we dont provide server support or Lag diagnosis...my suggestion if you cant assess a timing report yourself to extract the important diagnosible bits is to post it on Spigotmc either in the IRC channel or forums ...once you can define that its definitely minigames ...because I dont see any lag from minigames on that report...just be clear the only Tick I saw a long time on was the loading tick...which happens on server load...,,,and you have plugins producing much longer load times that minigames.

**Comment by Narimm** [comment]
You can reopen when you can actually post an issue  - PLEASE use the template....otherwise it will be closed
