### ISSUE TITLE
Bug: Fall damage is applied after leaving a game

### ISSUE THREAD

**Issue by orkun1675** [AddstarMC/Minigames#60]
If a player is in mid air (falling) when a minigame is over, they are teleported to the lobby, but the fall damage is still applied to the player. This damage should be cancelled because players who enter minigames with items loose their items like this.

**Comment by addstar** [comment]
This is a known issue with teleporting in general (not related to Minigames) but we could possibly put in a work around to cancel fall damage for 1-2 seconds after the game ends.

Unfortunately we dont have much time for working on Minigames lately, but if you are capable, please feel free to make the code changes and submit a PR for your changes. We are happy to review it.

Otherwise, we'll try to get to this issue when we have time. Sorry about this.

**Comment by Narimm** [comment]
Can you confirm fall damage is still an issue in the development versions thanks
